---
title: "female-pulse"
format: html
editor: visual
execute: 
  echoe: false
  message: false
---

## What is the difference in pulse rate between two randomly selected female students in this class?

### Wisdom - 
preceptor table (predictive, units: females, outcome: pulse) 
validity - inconsistency in measuring pulse, how/when the pulse measurement was taken ->
Population Table

### Justice - 
presentative
stability 
confoundedness

formula:pulse ~ 1

### Courage - 



Temperance -


```{r}
library(primer.data)
library(tidyverse)
library(rstanarm)
```
```{r}
x <- nhanes |>
  filter(gender == "Female") |>
  drop_na() |>
  select(gender, pulse)
```

```{r}
fit_obj <- stan_glm(data = x, 
                    formula = pulse ~ 1, 
                    family = gaussian, 
                    refresh = 0,
                    seed = 9)

newobs <- tibble(gender = c("female", "female"))

pp <- posterior_predict(fit_obj, newdata = newobs) |>
  as_tibble() |>
  mutate(diff = abs(`2` - `1`))

pp
```

```{r}
pp |>
  ggplot(aes(x = diff)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
  theme_classic() +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Posterior for average between two randomly selected \nfemale students",
       subtitle = "Most likely to be between 0 and 30 bpm",
       x = "Difference in pulse (bpm)",
       y = "Probability")
```

